server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: validate
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/security
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/security
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: spring_security
            client-secret: vXyPxGBT2kfzQWWoHuaOsNSgBibC1e19
            scope: openid